/*
  Warnings:

  - The values [MINIMO_DE_25_PORCENTO_DAS_RECEITAS_RESULTANTES_DE_IMPOSTOS_MDE] on the enum `DeducoesParaFinsDeLimitesConstitucionalTipo1718` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "DeducoesParaFinsDeLimitesConstitucionalTipo1718_new" AS ENUM ('RESULTADO_LIQUIDO_DAS_TRANSFERENCIAS_DO_FUNDEB', 'DESPESAS_CUSTEADAS_A_COMPLEMENTACAO_DO_FUNDEB_NO_EXERCICIO', 'RECEITA_DE_APLICACAO_FINANCEIRA_DOS_RECURSOS_DO_FUNDEB_ATE_BIM', 'DESPESAS_CUSTEADAS_SUPERAVIT_FINANCEIRO_DO_EXERCICIO_ANTERIOR', 'DESPESAS_CUSTEADAS_SUPERAVIT_EXERCICIO_ANTERIOR_OUTROS_IMPOSTOS', 'RESTOS_A_PAGAR_INSCRITOS_SEM_DISPONIBILIDADE_FINANCEIRA', 'CANCELAMENTO_RESTOS_PAGAR_INSCRITOS_DISPONIBILIDADE_FINANCEIRA', 'TOTAL_DE_DEDUCOES_PARA_FINS_DE_LIMITE_CONSTITUCIONAL', 'TOTAL_DE_DESPESAS_PARA_FINS_DE_LIMITE', 'PERCENTUAL_DE_APLICACAO_MDE_SOBRE_RECEITA_LIQUIDA_IMPOSTOS');
ALTER TABLE "DeducoesParaFinsDeLimitesConstitucional1718" ALTER COLUMN "tipo" TYPE "DeducoesParaFinsDeLimitesConstitucionalTipo1718_new" USING ("tipo"::text::"DeducoesParaFinsDeLimitesConstitucionalTipo1718_new");
ALTER TYPE "DeducoesParaFinsDeLimitesConstitucionalTipo1718" RENAME TO "DeducoesParaFinsDeLimitesConstitucionalTipo1718_old";
ALTER TYPE "DeducoesParaFinsDeLimitesConstitucionalTipo1718_new" RENAME TO "DeducoesParaFinsDeLimitesConstitucionalTipo1718";
DROP TYPE "DeducoesParaFinsDeLimitesConstitucionalTipo1718_old";
COMMIT;
