/*
  Warnings:

  - You are about to drop the column `depesasLiquidadasNoAno` on the `Despesa06` table. All the data in the column will be lost.
  - You are about to drop the column `depesasLiquidadasPercentual` on the `Despesa06` table. All the data in the column will be lost.
  - Added the required column `despesasLiquidadasNoAno` to the `Despesa06` table without a default value. This is not possible if the table is not empty.
  - Added the required column `despesasLiquidadasPercentual` to the `Despesa06` table without a default value. This is not possible if the table is not empty.

*/
-- CreateEnum
CREATE TYPE "ItemReceitaTipos0708" AS ENUM ('RECEITAS_DE_IMPOSTO', 'RECEITA_RESULTANTE_IMPOSTO_IPTU', 'IMPOSTO_PROPRIEDADE_PREDIAL_TERRITORIAL_URBANA_IPTU', 'MULTAS_JUROS_MORA_OUTROS_ENCARGOS_IPTU', 'DIVIDA_ATIVA_IPTU', 'MULTAS_JUROS_MORA_ATUALIZACAO_MONETARIA_DIVIDA_ATIVA_IPTU', 'RECEITA_RESULTANTE_ITBI', 'IMPOSTO_TRANSMISSAO_INTER_VIVOS_ITBI', 'MULTAS_JUROS_MORA_OUTROS_ENCARGOS_ITBI', 'DIVIDA_ATIVA_ITBI', 'MULTAS_JUROS_MORA_ATUALIZACAO_MONETARIA_DIVIDA_ATIVA_ITBI', 'RECEITA_RESULTANTE_ISS', 'IMPOSTO_SERVICOS_QUALQUER_NATUREZA_ISS', 'MULTAS_JUROS_MORA_OUTROS_ENCARGOS_ISS', 'DIVIDA_ATIVA_ISS', 'MULTAS_JUROS_MORA_ATUALIZACAO_MONETARIA_DIVIDA_ATIVA_ISS', 'RECEITA_RESULTANTE_IRRF', 'IMPOSTO_RENDA_RETIDO_FONTE_IRRF', 'MULTAS_JUROS_MORA_OUTROS_ENCARGOS_IRRF', 'DIVIDA_ATIVA_IRRF', 'MULTAS_JUROS_MORA_ATUALIZACAO_MONETARIA_DIVIDA_ATIVA_IRRF', 'RECEITAS_DE_TRANSFERENCIAS_CONSTITUCIONAIS_E_LEGAL', 'COTA_PARTE_FPM', 'COTA_PARTE_ICMS', 'ICMS_DESONERACAO', 'COTA_PARTE_IPI_EXPORTACAO', 'COTA_PARTE_ITR', 'COTA_PARTE_IPVA', 'COTA_PARTE_IOF_OURO', 'TOTAL_RECEITA_BRUTA_IMPOSTOS', 'TRANSFERENCIAS_FNDE', 'TRANSFERENCIAS_SALARIO_EDUCACAO', 'OUTRAS_TRANSFERENCIAS_FNDE', 'TRANSFERENCIAS_CONVENIOS_PROGRAMAS_EDUCACAO', 'RECEITA_OPERACOES_CREDITO_DESTINADA_EDUCACAO', 'OUTRAS_RECEITAS_DESTINADAS_EDUCACAO', 'TOTAL_OUTRAS_RECEITAS_DESTINADAS_ENSINO', 'RECEITAS_DESTINADAS_AO_FUNDEB', 'COTA_PARTE_FPM_DESTINADA_FUNDEB', 'COTA_PARTE_ICMS_DESTINADA_FUNDEB', 'ICMS_DESONERACAO_DESTINADA_FUNDEB', 'COTA_PARTE_IPI_EXPORTACAO_DESTINADA_FUNDEB', 'COTA_PARTE_ITR_DESTINADA_FUNDEB', 'COTA_PARTE_IPVA_DESTINADA_FUNDEB', 'RECEITAS_RECEBIDAS_DO_FUNDEB', 'TRANSFERENCIAS_RECURSOS_FUNDEB', 'COMPLEMENTACAO_UNIAO_FUNDEB', 'RECEITA_APLICACAO_FINANCEIRA_RECURSOS_FUNDEB', 'RESULTADO_LIQUIDO_TRANSFERENCIAS_FUNDEB', 'ACRESCIMO_RESULTANTE_TRANSFERENCIAS_FUNDEB', 'IMPOSTOS_E_TRANSFERENCIAS_DESTINADAS_MDE');

-- CreateEnum
CREATE TYPE "ItemDespesaTipos0708" AS ENUM ('FUNDEB_PAGAMENTO_PROFISSIONAIS_MAGISTERIO', 'FUNDEB_PAGAMENTO_PROFISSIONAIS_MAGISTERIO_EDUCACAO_INFANTIL', 'FUNDEB_PAGAMENTO_PROFISSIONAIS_MAGISTERIO_ENSINO_FUNDAMENTAL', 'FUNDEB_OUTRAS_DESPESAS', 'FUNDEB_OUTRAS_DESPESAS_EDUCACAO_INFANTIL', 'FUNDEB_OUTRAS_DESPESAS_ENSINO_FUNDAMENTAL', 'TOTAL_DESPESAS_FUNDEB', 'MDE_EDUCACAO_INFANTIL', 'MDE_EDUCACAO_INFANTIL_DESPESAS_CUSTEADAS_FUNDEB', 'MDE_EDUCACAO_INFANTIL_DESPESAS_CUSTEADAS_OUTROS_IMPOSTOS', 'MDE_ENSINO_FUNDAMENTAL', 'MDE_ENSINO_FUNDAMENTAL_DESPESAS_CUSTEADAS_FUNDEB', 'MDE_ENSINO_FUNDAMENTAL_DESPESAS_CUSTEADAS_OUTROS_IMPOSTOS', 'MDE_DESPESAS_ENSNO_MEDIO', 'MDE_DESPESAS_ENSINO_SUPERIOR', 'MDE_DESPESAS_ENSINO_PROFISSIONAL_NAO_INTEGRADO_ENSINO_REGULAR', 'MDE_OUTRAS_DESPESAS', 'TOTAL_DESPESAS_COM_ACOES_TIPICAS_MDE', 'CONTRIBUICAO_SOCIAL_SALARIO_EDUCACAO', 'RECURSOS_OPERACOES_DE_CREDITO', 'OUTROS_RECURSOS_DESTINADOS_A_EDUCACAO', 'TOTAL_OUTRAS_DESPESAS_CUSTEADAS_RECURSOS_DESTINADOS_MDE', 'TOTAL_DESPESAS_COM_ENSINO');

-- CreateEnum
CREATE TYPE "Minimo60PorCentoFundebTipo0708" AS ENUM ('MINIMO_60_PORCENTO_FUNDEB_REMUNERACAO_MAGISTERIO_EDUCACAO');

-- CreateEnum
CREATE TYPE "DeducoesAdicoesParaFinsLimiteConstitucionalTipo0708" AS ENUM ('RESULTADO_LIQUIDO_DAS_TRANSFERENCIAS_DO_FUNDEB', 'DESPESAS_CUSTEADAS_A_COMPLEMENTACAO_DO_FUNDEB_NO_EXERCICIO', 'RESTOS_A_PAGAR_INSCRITOS_SEM_DISPONIBILIDADE_FINANCEIRA', 'DESPESAS_VINCULADAS_SUPERAVIT_FINANCEIRO_DO_FUNDEF', 'CANCELAMENTO_RESTOS_PAGAR_INSCRITOS_DISPONIBILIDADE_FINANCEIRA', 'RECEITA_APLICACAO_FINANCEIRA_DOS_RECURSOS_FUNDEB_ATE_BIM', 'TOTAL_DE_DEDUCOES_ADICOES_PARA_FINS_DE_LIMITE_CONSTITUCIONAL', 'MINIMO_DE_25_PORCENTO_DAS_RECEITAS_RESULTANTES_DE_IMPOSTOS');

-- CreateEnum
CREATE TYPE "FluxoFinanceiroRecursosFundebTipo0708" AS ENUM ('SALDO_FINANCEIRO_DO_FUNDEF_ANO_ANTERIOR', 'INGRESSO_RECURSOS_FUNDEB_ATE_BIM', 'PAGAMENTOS_EFETUADOS_ATE_BIM', 'RECEITA_APLICACAO_FINANCEIRA_DOS_RECURSOS_FUNDEB_ATE_BIM', 'SALDO_FINANCEIRO_DO_FUNDEF_EXERCICIO_ATUAL');

-- CreateEnum
CREATE TYPE "InformacoesControleFinanceiroTipo0708" AS ENUM ('RESTOS_A_PAGAR_DE_DESPESA_MDE');

-- AlterTable
ALTER TABLE "Despesa06" DROP COLUMN "depesasLiquidadasNoAno",
DROP COLUMN "depesasLiquidadasPercentual",
ADD COLUMN     "despesasLiquidadasNoAno" DOUBLE PRECISION NOT NULL,
ADD COLUMN     "despesasLiquidadasPercentual" DOUBLE PRECISION NOT NULL;

-- CreateTable
CREATE TABLE "RelatorioMunicipal0708" (
    "id" SERIAL NOT NULL,
    "ano" TEXT NOT NULL,
    "codigoMunicipio" TEXT NOT NULL,

    CONSTRAINT "RelatorioMunicipal0708_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Receita0708" (
    "id" SERIAL NOT NULL,
    "tipo" "ItemReceitaTipos0708" NOT NULL,
    "previsaoInicial" DOUBLE PRECISION NOT NULL,
    "previsaoAtualizada" DOUBLE PRECISION NOT NULL,
    "receitasRealizadasNoAno" DOUBLE PRECISION NOT NULL,
    "receitasRealizadasPercentual" DOUBLE PRECISION NOT NULL,
    "relatorioMunicialId" INTEGER NOT NULL,

    CONSTRAINT "Receita0708_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Despesa0708" (
    "id" SERIAL NOT NULL,
    "tipo" "ItemDespesaTipos0708" NOT NULL,
    "dotacaoInicial" DOUBLE PRECISION NOT NULL,
    "dotacaoAtualizada" DOUBLE PRECISION NOT NULL,
    "despesasEmpenhadasNoAno" DOUBLE PRECISION NOT NULL,
    "despesasEmpenhadasPercentual" DOUBLE PRECISION NOT NULL,
    "relatorioMunicialId" INTEGER NOT NULL,

    CONSTRAINT "Despesa0708_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Minimo60PorCentoFundeb0708" (
    "id" SERIAL NOT NULL,
    "tipo" "Minimo60PorCentoFundebTipo0708" NOT NULL,
    "despesasRealizadasPercentual" DOUBLE PRECISION NOT NULL,
    "relatorioMunicialId" INTEGER NOT NULL,

    CONSTRAINT "Minimo60PorCentoFundeb0708_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DeducoesAdicoesParaFinsLimiteConstitucional0708" (
    "id" SERIAL NOT NULL,
    "tipo" "DeducoesAdicoesParaFinsLimiteConstitucionalTipo0708" NOT NULL,
    "valor" DOUBLE PRECISION NOT NULL,
    "relatorioMunicialId" INTEGER NOT NULL,

    CONSTRAINT "DeducoesAdicoesParaFinsLimiteConstitucional0708_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FluxoFinanceiroRecursosFundeb0708" (
    "id" SERIAL NOT NULL,
    "tipo" "FluxoFinanceiroRecursosFundebTipo0708" NOT NULL,
    "valor" DOUBLE PRECISION NOT NULL,
    "relatorioMunicialId" INTEGER NOT NULL,

    CONSTRAINT "FluxoFinanceiroRecursosFundeb0708_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "InformacoesControleFinanceiro0708" (
    "id" SERIAL NOT NULL,
    "tipo" "InformacoesControleFinanceiroTipo0708" NOT NULL,
    "saldoAteBimeste" DOUBLE PRECISION NOT NULL,
    "cancelado" DOUBLE PRECISION NOT NULL,
    "relatorioMunicialId" INTEGER NOT NULL,

    CONSTRAINT "InformacoesControleFinanceiro0708_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Receita0708_relatorioMunicialId_tipo_key" ON "Receita0708"("relatorioMunicialId", "tipo");

-- CreateIndex
CREATE UNIQUE INDEX "Despesa0708_relatorioMunicialId_tipo_key" ON "Despesa0708"("relatorioMunicialId", "tipo");

-- CreateIndex
CREATE UNIQUE INDEX "Minimo60PorCentoFundeb0708_relatorioMunicialId_tipo_key" ON "Minimo60PorCentoFundeb0708"("relatorioMunicialId", "tipo");

-- CreateIndex
CREATE UNIQUE INDEX "DeducoesAdicoesParaFinsLimiteConstitucional0708_relatorioMu_key" ON "DeducoesAdicoesParaFinsLimiteConstitucional0708"("relatorioMunicialId", "tipo");

-- CreateIndex
CREATE UNIQUE INDEX "FluxoFinanceiroRecursosFundeb0708_relatorioMunicialId_tipo_key" ON "FluxoFinanceiroRecursosFundeb0708"("relatorioMunicialId", "tipo");

-- CreateIndex
CREATE UNIQUE INDEX "InformacoesControleFinanceiro0708_relatorioMunicialId_tipo_key" ON "InformacoesControleFinanceiro0708"("relatorioMunicialId", "tipo");

-- AddForeignKey
ALTER TABLE "Receita0708" ADD CONSTRAINT "Receita0708_relatorioMunicialId_fkey" FOREIGN KEY ("relatorioMunicialId") REFERENCES "RelatorioMunicipal0708"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Despesa0708" ADD CONSTRAINT "Despesa0708_relatorioMunicialId_fkey" FOREIGN KEY ("relatorioMunicialId") REFERENCES "RelatorioMunicipal0708"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Minimo60PorCentoFundeb0708" ADD CONSTRAINT "Minimo60PorCentoFundeb0708_relatorioMunicialId_fkey" FOREIGN KEY ("relatorioMunicialId") REFERENCES "RelatorioMunicipal0708"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DeducoesAdicoesParaFinsLimiteConstitucional0708" ADD CONSTRAINT "DeducoesAdicoesParaFinsLimiteConstitucional0708_relatorioM_fkey" FOREIGN KEY ("relatorioMunicialId") REFERENCES "RelatorioMunicipal0708"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FluxoFinanceiroRecursosFundeb0708" ADD CONSTRAINT "FluxoFinanceiroRecursosFundeb0708_relatorioMunicialId_fkey" FOREIGN KEY ("relatorioMunicialId") REFERENCES "RelatorioMunicipal0708"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InformacoesControleFinanceiro0708" ADD CONSTRAINT "InformacoesControleFinanceiro0708_relatorioMunicialId_fkey" FOREIGN KEY ("relatorioMunicialId") REFERENCES "RelatorioMunicipal0708"("id") ON DELETE CASCADE ON UPDATE CASCADE;
