/*
  Warnings:

  - The values [FUNDEB_RENDIMENTO_APLICACAO_FINCANCEIRA_6_3_3] on the enum `ItemReceitaTipos21` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ItemReceitaTipos21_new" AS ENUM ('RECEITA_DE_IMPOSTOS', 'RECEITA_IPTU', 'RECEITA_ITBI', 'RECEITA_ISS', 'RECEITA_IRRF', 'RECEITA_TRANSFERENCIAS_CONSTITUCIONAIS', 'COTA_PARTE_FPM', 'COTA_PARTE_FPM_PARCELA_CF_B', 'OTA_PARTE_FPM_PARCELA_CF_D_E', 'COTA_PARTE_ICMS', 'COTA_PARTE_IPI_EXPORTACAO', 'COTA_PARTE_ITR', 'COTA_PARTE_IPVA', 'COTA_PARTE_IOF_OURO', 'COMPENSACOES_FINANCEIRAS', 'TOTAL_RECEITA_IMPOSTOS', 'TOTAL_DESTINADO_FUNDEB', 'VALOR_MINIMO_APLICADO_MDE', 'RECEITAS_RECEBIDAS_FUNDEB', 'FUNDEB_IMPOSTOS_TRANSFERENCIAS', 'FUNDEB_PRINCIPAL_6_1_1', 'FUNDEB_RENDIMENTO_APLICACAO_FINCANCEIRA_6_1_2', 'FUNDEB_COMPLEMENTACAO_UNIAO_VAAF', 'FUNDEB_PRINCIPAL_6_2_1', 'FUNDEB_RENDIMENTO_APLICACAO_FINCANCEIRA_6_2_2', 'FUNDEB_COMPLEMENTACAO_UNIAO_VAAT', 'FUNDEB_PRINCIPAL_6_3_1', 'FUNDEB_RENDIMENTO_APLICACAO_FINCANCEIRA_6_3_2', 'RESULTADO_LIQUIDO_TRANSFERENCIAS_FUNDEB', 'FIN_ENSINO_RECEITA_TRANSFERENCIAS_FNDE', 'FIN_ENSINO_SALARIO_EDUCACAO', 'FIN_ENSINO_PDDE', 'FIN_ENSINO_PNAE', 'FIN_ENSINO_PNATE', 'FIN_ENSINO_OUTRAS_TRANSFERENCIAS_FNDE', 'FIN_ENSINO_RECEITA_TRANSFERENCIAS_CONVENIOS', 'FIN_ENSINO_RECEITA_ROYALTIES_DESTINADOS_EDUCACAO', 'FIN_ENSINO_RECEITA_OPERACOES_CREDITO_EDUCACAO', 'FIN_ENSINO_OUTRAS_RECEITAS', 'FIN_ENSINO_TOTAL_RECEITAS_ADICIONAIS');
ALTER TABLE "Receita21" ALTER COLUMN "tipo" TYPE "ItemReceitaTipos21_new" USING ("tipo"::text::"ItemReceitaTipos21_new");
ALTER TYPE "ItemReceitaTipos21" RENAME TO "ItemReceitaTipos21_old";
ALTER TYPE "ItemReceitaTipos21_new" RENAME TO "ItemReceitaTipos21";
DROP TYPE "ItemReceitaTipos21_old";
COMMIT;
