/*
  Warnings:

  - The values [MDE_DESPESAS_ENSNO_MEDIO] on the enum `ItemDespesaTipos0708` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ItemDespesaTipos0708_new" AS ENUM ('FUNDEB_PAGAMENTO_PROFISSIONAIS_MAGISTERIO', 'FUNDEB_PAGAMENTO_PROFISSIONAIS_MAGISTERIO_EDUCACAO_INFANTIL', 'FUNDEB_PAGAMENTO_PROFISSIONAIS_MAGISTERIO_ENSINO_FUNDAMENTAL', 'FUNDEB_OUTRAS_DESPESAS', 'FUNDEB_OUTRAS_DESPESAS_EDUCACAO_INFANTIL', 'FUNDEB_OUTRAS_DESPESAS_ENSINO_FUNDAMENTAL', 'TOTAL_DESPESAS_FUNDEB', 'MDE_EDUCACAO_INFANTIL', 'MDE_EDUCACAO_INFANTIL_DESPESAS_CUSTEADAS_FUNDEB', 'MDE_EDUCACAO_INFANTIL_DESPESAS_CUSTEADAS_OUTROS_IMPOSTOS', 'MDE_ENSINO_FUNDAMENTAL', 'MDE_ENSINO_FUNDAMENTAL_DESPESAS_CUSTEADAS_FUNDEB', 'MDE_ENSINO_FUNDAMENTAL_DESPESAS_CUSTEADAS_OUTROS_IMPOSTOS', 'MDE_DESPESAS_ENSINO_MEDIO', 'MDE_DESPESAS_ENSINO_SUPERIOR', 'MDE_DESPESAS_ENSINO_PROFISSIONAL_NAO_INTEGRADO_ENSINO_REGULAR', 'MDE_OUTRAS_DESPESAS', 'TOTAL_DESPESAS_COM_ACOES_TIPICAS_MDE', 'CONTRIBUICAO_SOCIAL_SALARIO_EDUCACAO', 'RECURSOS_OPERACOES_DE_CREDITO', 'OUTROS_RECURSOS_DESTINADOS_A_EDUCACAO', 'TOTAL_OUTRAS_DESPESAS_CUSTEADAS_RECURSOS_DESTINADOS_MDE', 'TOTAL_DESPESAS_COM_ENSINO');
ALTER TABLE "Despesa0708" ALTER COLUMN "tipo" TYPE "ItemDespesaTipos0708_new" USING ("tipo"::text::"ItemDespesaTipos0708_new");
ALTER TYPE "ItemDespesaTipos0708" RENAME TO "ItemDespesaTipos0708_old";
ALTER TYPE "ItemDespesaTipos0708_new" RENAME TO "ItemDespesaTipos0708";
DROP TYPE "ItemDespesaTipos0708_old";
COMMIT;
