/*
  Warnings:

  - The values [PROFISSIONAIS_DA_EDUCACAO_BASICA_EDUCACAO_INFANTIL,TOTAL_OUTRAS_DESPESAS_ENSINO_PROFISSIONAL_NAO_INTEGRADO] on the enum `ItemDespesaEstadualTipos23` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the `RestosAPagarExerciciosAntDisponibilidadeFinanceiraFundebEstadua` table. If the table is not empty, all the data it contains will be lost.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ItemDespesaEstadualTipos23_new" AS ENUM ('TOTAL_DAS_DESPESAS_COM_RECURSOS_DO_FUNDEB', 'PROFISSIONAIS_DA_EDUCACAO_BASICA', 'PROFISSIONAIS_DA_EDUCACAO_BASICA_ENSINO_FUNDAMENTAL', 'PROFISSIONAIS_DA_EDUCACAO_BASICA_ENSINO_MEDIO', 'PROFISSIONAIS_DA_EDUCACAO_BASICA_EDUCACAO_DE_JOVENS_ADULTOS', 'PROFISSIONAIS_DA_EDUCACAO_BASICA_EDUCACAO_ESPECIAL', 'PROFISSIONAIS_DA_EDUCACAO_BASICA_ADMINISTRACAO_GERAL', 'OUTRAS_DESPESAS', 'OUTRAS_DESPESAS_EDUCACAO_INFANTIL', 'OUTRAS_DESPESAS_ENSINO_FUNDAMENTAL', 'OUTRAS_DESPESAS_EDUCACAO_DE_JOVENS_E_ADULTOS', 'OUTRAS_DESPESAS_EDUCACAO_ESPECIAL', 'OUTRAS_DESPESAS_ADMINISTRACAO_GERAL', 'OUTRAS_DESPESAS_TRANSPORTE_ESCOLAR', 'OUTRAS_DESPESAS_OUTRAS', 'TOTAL_DESPESAS_MDE_CUSTEADAS_COM_RECEITAS_IMPOSTOS', 'MDE_COM_RECEITAS_IMPOSTOS_EDUCACAO_INFANTIL', 'MDE_COM_RECEITAS_IMPOSTOS_ENSINO_FUNDAMENTAL', 'MDE_COM_RECEITAS_IMPOSTOS_ENSINO_MEDIO', 'MDE_COM_RECEITAS_IMPOSTOS_ENSINO_SUPERIOR', 'MDE_COM_RECEITAS_IMPOSTOS_ENSINO_PROFISSIONAL', 'MDE_COM_RECEITAS_IMPOSTOS_EDUCACAO_DE_JOVENS_E_ADULTOS', 'MDE_COM_RECEITAS_IMPOSTOS_EDUCACAO_ESPECIAL', 'MDE_COM_RECEITAS_IMPOSTOS_ADMINISTRACAO_GERAL', 'MDE_COM_RECEITAS_IMPOSTOS_TRANSPORTE_ESCOLAR', 'MDE_COM_RECEITAS_IMPOSTOS_OUTRAS', 'TOTAL_DESPESAS_COM_ACOES_TIPICAS_MDE_CUSTEADAS_IMPOSTOS_FUNDEB', 'ACOES_TIPICAS_MDE_EDUCACAO_INFANTIL', 'ACOES_TIPICAS_MDE_CRECHE', 'ACOES_TIPICAS_MDE_PRE_ESCOLA', 'ACOES_TIPICAS_MDE_ENSINO_FUNDAMENTAL', 'ACOES_TIPICAS_MDE_ENSINO_MEDIO', 'ACOES_TIPICAS_MDE_ENSINO_SUPERIOR', 'ACOES_TIPICAS_MDE_ENSINO_PROFISSIONAL_NAO_INTEGRADO', 'TOTAL_OUTRAS_DESPESAS_COM_EDUCACAO', 'TOTAL_OUTRAS_DESPESAS_ENSINO_FUNDAMENTAL', 'TOTAL_OUTRAS_DESPESAS_EDUCACAO_INFANTIL', 'TOTAL_OUTRAS_DESPESAS_ENSINO_MEDIO', 'TOTAL_OUTRAS_DESPESAS_ENSINO_SUPERIOR', 'TOTAL_OUTRAS_DESPESAS_ENSINO_PROFISSIONAL', 'TOTAL_OUTRAS_DESPESAS_ENSINO_DE_JOVENS_E_ADULTOS', 'TOTAL_OUTRAS_DESPESAS_EDUCACAO_ESPECIAL', 'TOTAL_OUTRAS_DESPESAS_OUTRAS', 'TOTAL_GERAL_DESPESAS_COM_EDUCACAO', 'DESPESAS_CORRENTES', 'PESSOAL_ATIVO', 'PESSOAL_INATIVO', 'TRANSFERENCIAS_INSTITUICOES_COMUNITARIAS', 'OUTRAS_DESPESAS_CORRENTES', 'DESPESAS_DE_CAPITAL', 'TRANSFERENCIAS_INSTITUICOES_COMUNITARIAS_CAPITAL', 'OUTRAS_DESPESAS_CAPITAL');
ALTER TABLE "DespesaEstadual23" ALTER COLUMN "tipo" TYPE "ItemDespesaEstadualTipos23_new" USING ("tipo"::text::"ItemDespesaEstadualTipos23_new");
ALTER TYPE "ItemDespesaEstadualTipos23" RENAME TO "ItemDespesaEstadualTipos23_old";
ALTER TYPE "ItemDespesaEstadualTipos23_new" RENAME TO "ItemDespesaEstadualTipos23";
DROP TYPE "ItemDespesaEstadualTipos23_old";
COMMIT;

-- DropForeignKey
ALTER TABLE "RestosAPagarExerciciosAntDisponibilidadeFinanceiraFundebEstadua" DROP CONSTRAINT "RestosAPagarExerciciosAntDisponibilidadeFinanceiraFundebEs_fkey";

-- DropTable
DROP TABLE "RestosAPagarExerciciosAntDisponibilidadeFinanceiraFundebEstadua";

-- CreateTable
CREATE TABLE "RestosAPagarExerciciosAntDisponibilidadeFinanceiraFundebEstadual21" (
    "id" SERIAL NOT NULL,
    "tipo" "RestosAPagarExerciciosAntDisponibilidadeFinanceiraFundebTipos21" NOT NULL,
    "saldoInicial" DOUBLE PRECISION NOT NULL,
    "rpLiquidados" DOUBLE PRECISION NOT NULL,
    "rpPagos" DOUBLE PRECISION NOT NULL,
    "rpCancelados" DOUBLE PRECISION NOT NULL,
    "saldoFinal" DOUBLE PRECISION NOT NULL,
    "relatorioEstadualId" INTEGER NOT NULL,

    CONSTRAINT "RestosAPagarExerciciosAntDisponibilidadeFinanceiraFundebEs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "RestosAPagarExerciciosAntDisponibilidadeFinanceiraFundebEst_key" ON "RestosAPagarExerciciosAntDisponibilidadeFinanceiraFundebEstadual21"("relatorioEstadualId", "tipo");

-- AddForeignKey
ALTER TABLE "RestosAPagarExerciciosAntDisponibilidadeFinanceiraFundebEstadual21" ADD CONSTRAINT "RestosAPagarExerciciosAntDisponibilidadeFinanceiraFundebEs_fkey" FOREIGN KEY ("relatorioEstadualId") REFERENCES "RelatorioEstadual21"("id") ON DELETE CASCADE ON UPDATE CASCADE;
