// src/prisma/seed.ts

import { PrismaClient } from './generated/educacao-client';
import * as fs from 'fs';
import * as path from 'path';
import { parse } from 'csv-parse';

const prisma = new PrismaClient();

const arquivoCSV = 'C:/teste_salvamento/dados_2024_piaui.csv';

// A funçãoaceita a lista de colunas permitidas como argumento/
function processaLinha(row: any, colunasPermitidas: string[]): Record<string, any> {
  const record: Record<string, any> = {};

  // Itera sobre a lista de colunas permitidas
  for (const coluna of colunasPermitidas) {
    // Verifica se a linha do CSV realmente possui essa coluna.
    if (Object.prototype.hasOwnProperty.call(row, coluna)) {
      let value = row[coluna];

      if (value === '') {
        value = null;
      } else if (typeof value === 'string') {
        const num = Number(value.replace(',', '.'));
        value = isNaN(num) ? value : num;
      }
      
      // Adiciona ao registro final apenas se a coluna for permitida.
      record[coluna] = value;
    }
    // Se a coluna permitida não existir na linha do CSV, ela simplesmente não será adicionada ao objeto,
    // o que é geralmente o comportamento desejado.
  }
  return record;
}


async function main() {
  // lista de colunas permitidas.
  // Estes nomes devem ser EXATAMENTE iguais aos campos no seu model do Prisma
  // e aos nomes das colunas no cabeçalho do CSV.
  const colunasPermitidas = [
'NO_ENTIDADE','CO_MUNICIPIO','NO_MUNICIPIO','CO_UF', 'SG_UF', 'TP_DEPENDENCIA','TP_LOCALIZACAO','ANO', 'IN_LOCAL_FUNC_PREDIO_ESCOLAR', 'TP_OCUPACAO_PREDIO_ESCOLAR', 'IN_LOCAL_FUNC_SALAS_EMPRESA',
'IN_LOCAL_FUNC_SOCIOEDUCATIVO', 'IN_LOCAL_FUNC_UNID_PRISIONAL', 'IN_LOCAL_FUNC_PRISIONAL_SOCIO',
'IN_LOCAL_FUNC_TEMPLO_IGREJA', 'IN_LOCAL_FUNC_CASA_PROFESSOR', 'IN_LOCAL_FUNC_GALPAO', 'TP_OCUPACAO_GALPAO',
'IN_LOCAL_FUNC_SALAS_OUTRA_ESC', 'IN_LOCAL_FUNC_OUTROS', 'IN_PREDIO_COMPARTILHADO', 'IN_AGUA_POTAVEL',
'IN_AGUA_FILTRADA', 'IN_AGUA_REDE_PUBLICA', 'IN_AGUA_POCO_ARTESIANO', 'IN_AGUA_CACIMBA', 'IN_AGUA_FONTE_RIO',
'IN_AGUA_INEXISTENTE', 'IN_AGUA_CARRO_PIPA', 'IN_ENERGIA_REDE_PUBLICA', 'IN_ENERGIA_GERADOR',
'IN_ENERGIA_GERADOR_FOSSIL', 'IN_ENERGIA_RENOVAVEL', 'IN_ENERGIA_OUTROS', 'IN_ENERGIA_INEXISTENTE',
'IN_ESGOTO_REDE_PUBLICA', 'IN_ESGOTO_FOSSA', 'IN_ESGOTO_FOSSA_SEPTICA', 'IN_ESGOTO_FOSSA_COMUM',
'IN_ESGOTO_INEXISTENTE', 'IN_LIXO_SERVICO_COLETA', 'IN_LIXO_QUEIMA', 'IN_LIXO_ENTERRA',
'IN_LIXO_DESTINO_FINAL_PUBLICO', 'IN_LIXO_JOGA_OUTRA_AREA', 'IN_LIXO_DESCARTA_OUTRA_AREA', 'IN_LIXO_RECICLA',
'IN_LIXO_OUTROS', 'IN_TRATAMENTO_LIXO_SEPARACAO', 'IN_TRATAMENTO_LIXO_REUTILIZA', 'IN_TRATAMENTO_LIXO_RECICLAGEM',
'IN_TRATAMENTO_LIXO_INEXISTENTE', 'IN_BANHEIRO', 'IN_BANHEIRO_FORA_PREDIO', 'IN_BANHEIRO_DENTRO_PREDIO',
'IN_BANHEIRO_PNE', 'IN_BANHEIRO_EI', 'IN_BANHEIRO_FUNCIONARIOS', 'IN_BANHEIRO_CHUVEIRO', 'IN_DEPENDENCIAS_PNE',
'IN_ACESSIBILIDADE_INEXISTENTE', 'IN_ACESSIBILIDADE_CORRIMAO', 'IN_ACESSIBILIDADE_ELEVADOR',
'IN_ACESSIBILIDADE_PISOS_TATEIS', 'IN_ACESSIBILIDADE_VAO_LIVRE', 'IN_ACESSIBILIDADE_RAMPAS',
'IN_ACESSIBILIDADE_SINAL_SONORO', 'IN_ACESSIBILIDADE_SINAL_TATIL', 'IN_ACESSIBILIDADE_SINAL_VISUAL',
'IN_BIBLIOTECA_SALA_LEITURA', 'IN_BIBLIOTECA', 'IN_SALA_LEITURA', 'IN_COZINHA', 'IN_LABORATORIO_CIENCIAS',
'IN_LABORATORIO_INFORMATICA', 'IN_LABORATORIO_EDUC_PROF', 'IN_QUADRA_ESPORTES_COBERTA',
'IN_QUADRA_ESPORTES_DESCOBERTA', 'IN_QUADRA_ESPORTES', 'IN_SALA_ATENDIMENTO_ESPECIAL', 'IN_AUDITORIO',
'IN_PATIO_COBERTO', 'IN_PATIO_DESCOBERTO', 'IN_PISCINA', 'IN_SALA_DIRETORIA', 'IN_SALA_PROFESSOR',
'IN_SALA_SECRETARIA', 'IN_REFEITORIO', 'IN_ALMOXARIFADO', 'IN_DESPENSA', 'IN_AREA_VERDE', 'IN_BERCARIO',
'IN_DORMITORIO_ALUNO', 'IN_PARQUE_INFANTIL', 'IN_SALA_ATELIE_ARTES', 'IN_SALA_MUSICA_CORAL',
'IN_SALA_ESTUDIO_DANCA', 'IN_SALA_MULTIUSO', 'IN_SALA_ESTUDIO_GRAVACAO', 'IN_SALA_OFICINAS_EDUC_PROF',
'IN_SALA_REPOUSO_ALUNO', 'IN_TERREIRAO', 'IN_VIVEIRO', 'QT_SALAS_EXISTENTES', 'QT_SALAS_UTILIZADAS',
'QT_SALAS_UTILIZADAS_DENTRO', 'QT_SALAS_UTILIZADAS_FORA', 'QT_SALAS_UTILIZA_CLIMATIZADAS',
'QT_SALAS_UTILIZADAS_ACESSIVEIS', 'IN_EQUIP_TV', 'IN_EQUIP_VIDEOCASSETE', 'IN_EQUIP_DVD', 'IN_EQUIP_PARABOLICA',
'IN_EQUIP_COPIADORA', 'IN_EQUIP_RETROPROJETOR', 'IN_EQUIP_IMPRESSORA', 'IN_EQUIP_IMPRESSORA_MULT',
'IN_EQUIP_SOM', 'IN_EQUIP_PROJETOR', 'IN_EQUIP_MULTIMIDIA', 'IN_EQUIP_FAX', 'IN_EQUIP_FOTO', 'IN_EQUIP_SCANNER',
'IN_EQUIP_NENHUM', 'IN_EQUIP_LOUSA_DIGITAL', 'QT_EQUIP_TV', 'QT_EQUIP_VIDEOCASSETE', 'QT_EQUIP_DVD',
'QT_EQUIP_PARABOLICA', 'QT_EQUIP_COPIADORA', 'QT_EQUIP_RETROPROJETOR', 'QT_EQUIP_IMPRESSORA',
'QT_EQUIP_IMPRESSORA_MULT', 'QT_EQUIP_SOM', 'QT_EQUIP_PROJETOR', 'QT_EQUIP_MULTIMIDIA', 'QT_EQUIP_FAX',
'QT_EQUIP_FOTO', 'QT_EQUIP_LOUSA_DIGITAL', 'IN_COMPUTADOR', 'QT_COMPUTADOR', 'QT_COMP_ADMINISTRATIVO',
'QT_COMP_ALUNO', 'IN_DESKTOP_ALUNO', 'QT_DESKTOP_ALUNO', 'IN_COMP_PORTATIL_ALUNO', 'QT_COMP_PORTATIL_ALUNO',
'IN_TABLET_ALUNO', 'QT_TABLET_ALUNO', 'IN_INTERNET', 'IN_INTERNET_APRENDIZAGEM', 'IN_INTERNET_ADMINISTRATIVO',
'IN_INTERNET_ALUNOS', 'IN_INTERNET_COMUNIDADE', 'IN_ACESSO_INTERNET_COMPUTADOR',
'IN_ACESSO_INTERNET_DISP_PESSOAIS', 'TP_REDE_LOCAL', 'IN_BANDA_LARGA', 'IN_MATERIAL_ESP_NAO_UTILIZA',
'IN_MATERIAL_ESP_PEDAGOGICO', 'IN_MATERIAL_ESP_ARTES', 'IN_MATERIAL_ESP_AUDIOVISUAIS', 'IN_MATERIAL_ESP_AUDITIVOS',
'IN_MATERIAL_ESP_BIOLOGIA', 'IN_MATERIAL_ESP_BRINQUEDOS', 'IN_MATERIAL_ESP_CIENCIAS', 'IN_MATERIAL_ESP_CINEMA',
'IN_MATERIAL_ESP_DISCIPLINAR', 'IN_MATERIAL_ESP_FISICA', 'IN_MATERIAL_ESP_FOTO', 'IN_MATERIAL_ESP_INFORMATICA',
'IN_MATERIAL_ESP_JOGOS', 'IN_MATERIAL_ESP_JORNAIS', 'IN_MATERIAL_ESP_LIVROS_DIDAT', 'IN_MATERIAL_ESP_LIVROS_LITER',
'IN_MATERIAL_ESP_MAPAS', 'IN_MATERIAL_ESP_MUSICA', 'IN_MATERIAL_ESP_OUTROS', 'IN_MATERIAL_ESP_QUIMICA',
'IN_MATERIAL_ESP_REVISTAS', 'IN_MATERIAL_ESP_QUILOMBOLA', 'IN_MATERIAL_ESP_INDIGENA', 'IN_MATERIAL_PED_MULTIMIDIA',
'IN_MATERIAL_PED_INFANTIL', 'IN_MATERIAL_PED_CIENTIFICO', 'IN_MATERIAL_PED_DIFUSAO', 'IN_MATERIAL_PED_MUSICAL',
'IN_MATERIAL_PED_JOGOS', 'IN_MATERIAL_PED_ARTISTICAS', 'IN_MATERIAL_PED_PROFISSIONAL', 'IN_MATERIAL_PED_DESPORTIVA',
'IN_MATERIAL_PED_INDIGENA', 'IN_MATERIAL_PED_ETNICO', 'IN_MATERIAL_PED_CAMPO', 'IN_MATERIAL_PED_BIL_SURDOS',
'IN_MATERIAL_PED_QUILOMBOLA', 'IN_MATERIAL_PED_AGRICOLA', 'IN_MATERIAL_PED_EDU_ESP', 'IN_MATERIAL_PED_NENHUM',
'IN_ALIMENTACAO', 'IN_ATIV_COMPLEMENTAR', 'IN_FUNDEB', 'IN_REGULAR_CLASSE_COMUM', 'IN_REGULAR_CLASSE_ESP',
'IN_ESP_CLASSE_COMUM', 'IN_ESP_CLASSE_ESP', 'IN_EJA_CLASSE_COMUM', 'IN_EJA_CLASSE_ESP', 'CO_LINGUA_INDIGENA_1',
'CO_LINGUA_INDIGENA_2', 'CO_LINGUA_INDIGENA_3', 'IN_AREA_PLANTIO', 'IN_DEPENDENCIAS_OUTRAS',
'IN_DORMITORIO_PROFESSOR', 'IN_EDUCACAO_INDIGENA', 'IN_LAVANDERIA', 'TP_AEE', 'TP_ATIVIDADE_COMPLEMENTAR',
'TP_INDIGENA_LINGUA', 'IN_MEDIACAO_PRESENCIAL', 'IN_MEDIACAO_SEMIPRESENCIAL', 'IN_MEDIACAO_EAD',
'IN_QUADRA_ESPORTES_PNE', 'IN_SANITARIO_PNE', 'IN_SANITARIO', 'IN_SANITARIO_FORA_PREDIO', 'IN_SANITARIO_DENTRO_PREDIO',
'IN_SANITARIO_CHUVEIRO', 'IN_PROF_CLASSE_COMUM', 'IN_PROF_CLASSE_ESP','IN_MEDIACAO_PRESENCIAL', 'IN_MEDIACAO_SEMIPRESENCIAL', 'IN_MEDIACAO_EAD',
'IN_ALIMENTACAO', 'IN_ATIV_COMPLEMENTAR', 'IN_FUNDEB', 'IN_REGULAR_CLASSE_COMUM', 'IN_REGULAR_CLASSE_ESP',
'IN_ESP_CLASSE_COMUM', 'IN_ESP_CLASSE_ESP', 'IN_EJA_CLASSE_COMUM', 'IN_EJA_CLASSE_ESP', 'CO_LINGUA_INDIGENA_1',
'CO_LINGUA_INDIGENA_2', 'CO_LINGUA_INDIGENA_3', 'IN_AREA_PLANTIO', 'IN_DEPENDENCIAS_OUTRAS',
'IN_DORMITORIO_PROFESSOR', 'IN_EDUCACAO_INDIGENA', 'IN_LAVANDERIA', 'TP_AEE', 'TP_ATIVIDADE_COMPLEMENTAR',
'TP_INDIGENA_LINGUA', 'IN_QUADRA_ESPORTES_PNE', 'IN_SANITARIO_PNE', 'IN_SANITARIO', 'IN_SANITARIO_FORA_PREDIO',
'IN_SANITARIO_DENTRO_PREDIO', 'IN_SANITARIO_CHUVEIRO', 'IN_PROF_CLASSE_COMUM', 'IN_PROF_CLASSE_ESP'


  ];

  console.log(`Iniciando o seed para o arquivo: ${path.basename(arquivoCSV)}...`);
  console.log(`Processando apenas ${colunasPermitidas.length} colunas permitidas.`);

  const BATCH_SIZE = 2000;
  let recordsBatch: any[] = [];
  let totalInserido = 0;

  console.log(`--- Processando arquivo: ${path.basename(arquivoCSV)} ---`);

  const parser = fs.createReadStream(arquivoCSV)
    .pipe(parse({ 
      delimiter: ';',
      columns: true,
      trim: true,
      bom: true
    }));
  
  for await (const row of parser) {
    //lista de permitidos para a função de processamento.
    const recordFormatado = processaLinha(row, colunasPermitidas);
    recordsBatch.push(recordFormatado);

    if (recordsBatch.length >= BATCH_SIZE) {
      await prisma.censoEscolarInfraestrutura.createMany({ 
        data: recordsBatch,
        skipDuplicates: true,
      });
      totalInserido += recordsBatch.length;
      console.log(`${totalInserido} registros inseridos...`);
      recordsBatch = [];
    }
  }

  if (recordsBatch.length > 0) {
    await prisma.censoEscolarInfraestrutura.createMany({ 
      data: recordsBatch,
      skipDuplicates: true,
    });
    totalInserido += recordsBatch.length;
  }

  console.log(`Arquivo ${path.basename(arquivoCSV)} finalizado. Total de ${totalInserido} registros inseridos.`);
  console.log('\n✅ Seed finalizado com sucesso!');
}

main()
  .catch((e) => {
    console.error('Ocorreu um erro durante o seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });